### ISSUE TITLE
Cant receive archive data

### ISSUE THREAD

**Issue by versionCollector** [Fantom-foundation/go-opera#231]
**Describe the bug**
Unable to get historical data from node.

I have synced node from genesis and downloaded archive data accordint to this issue https://github.com/Fantom-foundation/go-opera/issues/153
https://docs.fantom.foundation/tutorials/transaction-tracing-api says that node must be started with ```--tracenode``` parametr, and ```trace``` namespace should be enabled in ```http.api```. But whenever I try to launch the node with ```tracenode``` argument, it gives me error. Even ```opera --help``` does not display ```--tracenode``` as available flag. ```trace``` namespace is also unavailable.

**To Reproduce**
opera --genesis /path/to/genesis.g --tracenode -http --http.api=net,ftm,eth,debug,web3,txpool,sfc,dag,trace

**Expected behavior**
Node runs without any errors.

**Logs**
```--http.api=net,ftm,eth,debug,web3,txpool,sfc,dag,trace```
```
INFO [02-01|14:52:07.151] Maximum peer count                       total=50
INFO [02-01|14:52:07.151] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [02-01|14:52:07.151] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
INFO [02-01|14:52:19.832] Genesis is already written               hash=0x4a53c5445584b3bfc20dbfb2ec18ae20037c716f3ba2d9e1da768a9deca17cb4
WARN [02-01|14:52:19.832] Sanitizing invalid parameter MinPrice of gasprice oracle provided=0 updated=0
INFO [02-01|14:52:19.834] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-01|14:52:19.834] Regenerated local transaction journal    transactions=0 accounts=0
INFO [02-01|14:52:19.835] Starting peer-to-peer node               instance=go-opera/v1.0.2-rc.5-10ca6692-1630082373/linux-amd64/go1.14.15
INFO [02-01|14:52:19.837] Transaction pool price threshold updated price=131,081,025,000
INFO [02-01|14:52:19.875] New local node record                    seq=5811 id=ad588b7bf57b4692 ip=127.0.0.1 udp=5050 tcp=5050
INFO [02-01|14:52:19.899] Started P2P networking                   self=enode://3742d5155d33c4e809f35a0eaab4b7ad39edd8bac35c10f5304c01837ae6e4ef4e191a0fce1b3705db04b583e50c154d907a67d7e6620639de052a7a4fd6529c@127.0.0.1:5050
INFO [02-01|14:52:19.899] IPC endpoint opened                      url=/root/.opera/opera.ipc
ERROR[02-01|14:52:19.900] Unavailable modules in HTTP API list     unavailable=[trace] available="[admin debug web3 eth dag txpool personal sfc abft ftm net]"
```
```--tracenode```
```
`flag provided but not defined: -tracenode
```

**Comment by versionCollector** [comment]
Methods from ```trace``` namespace are not available. I have also tried methods like ```debug_traceBlockByNumber``` and ```debug_traceTransaction``` but even with enabled ```debug``` namespace I receive error messages:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32601,
        "message": "the method debug_traceBlockByNumber does not exist/is not available"
    }
}
```

**Comment by HonzaDajc** [comment]
Hello @versionCollector, can you please send the whole starting command for opera? And also new log after you have used `release/txtracing/1.0.2-rc.7` version. And maybe also log from console after you have node running and run attach command `opera attach --datadir=<path to your data directory>`

**Comment by versionCollector** [comment]
The node stopped working again, but now with internal error
Node version: ```release/txtracing/1.0.2-rc.7```
Launch arguments:
```
--tracenode
--nousb
--genesis=/fct/config/mainnet
--rpc.txfeecap=0
--http
--http.corsdomain=*
--http.vhosts=*
--http.addr=0.0.0.0
--http.port=8545
--http.api=net,ftm,eth,debug,web3,txpool,sfc,dag,trace,
--ws
--ws.addr=0.0.0.0
--ws.port=8546
--ws.api=net,ftm,eth,debug,web3,txpool,sfc,dag,trace,
--ws.origins=*
--snapshot=false
```
Logs:
```
INFO [02-07|11:52:44.811] Maximum peer count                       total=50
INFO [02-07|11:52:44.811] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [02-07|11:52:44.811] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
INFO [02-07|11:52:57.032] Genesis is already written               hash=0x4a53c5445584b3bfc20dbfb2ec18ae20037c716f3ba2d9e1da768a9deca17cb4
WARN [02-07|11:52:57.032] Sanitizing invalid parameter MinPrice of gasprice oracle provided=0 updated=0
INFO [02-07|11:52:57.034] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-07|11:52:57.034] Regenerated local transaction journal    transactions=0 accounts=0
INFO [02-07|11:52:57.034] Starting peer-to-peer node               instance=go-opera/v1.0.2-rc.7-04c48725-1643795904/linux-amd64/go1.14.15
INFO [02-07|11:52:57.036] Transaction pool price threshold updated price=219,574,200,000
INFO [02-07|11:52:57.060] New local node record                    seq=15060 id=ad588b7bf57b4692 ip=127.0.0.1 udp=5050 tcp=5050
INFO [02-07|11:52:57.079] Started P2P networking                   self=enode://3742d5155d33c4e809f35a0eaab4b7ad39edd8bac35c10f5304c01837ae6e4ef4e191a0fce1b3705db04b583e50c154d907a67d7e6620639de052a7a4fd6529c@127.0.0.1:5050
INFO [02-07|11:52:57.080] IPC endpoint opened                      url=/root/.opera/opera.ipc
INFO [02-07|11:52:57.081] HTTP server started                      endpoint=[::]:8545 prefix= cors=* vhosts=*
INFO [02-07|11:52:57.081] WebSocket enabled                        url=ws://[::]:8546
INFO [02-07|11:52:58.202] New events summary                       new=1 last_id=78183:2903:00fa66 age=3d18h44m t=1.116ms
INFO [02-07|11:52:58.260] Transaction pool price threshold updated price=219,530,550,000
INFO [02-07|11:52:58.263] New block                                index=29897842 id=78183:2891:f42fc7 gas_used=382,225 txs=3/0 age=3d18h44m t=49.714ms
INFO [02-07|11:52:58.336] New block                                index=29897843 id=78183:2904:abb58c gas_used=1,554,175 txs=4/0 age=3d18h44m t=73.421ms
INFO [02-07|11:52:58.427] New block                                index=29897844 id=78183:2915:866377 gas_used=1,267,644 txs=7/1 age=3d18h44m t=90.830ms
INFO [02-07|11:52:58.457] New block                                index=29897845 id=78183:2926:008579 gas_used=785,040   txs=3/0 age=3d18h44m t=30.160ms
INFO [02-07|11:52:58.556] New block                                index=29897846 id=78183:2932:725908 gas_used=1,298,140 txs=4/0 age=3d18h44m t=92.380ms
INFO [02-07|11:52:58.612] New block                                index=29897847 id=78183:2943:3d0351 gas_used=1,546,411 txs=6/0 age=3d18h44m t=56.474ms
INFO [02-07|11:52:58.654] New block                                index=29897848 id=78183:2955:933b38 gas_used=437,753   txs=6/0 age=3d18h44m t=41.817ms
INFO [02-07|11:52:58.699] New block                                index=29897849 id=78183:2960:32f1c2 gas_used=616,396   txs=5/0 age=3d18h44m t=44.309ms
INFO [02-07|11:52:58.812] New block                                index=29897850 id=78183:2972:5e9719 gas_used=2,189,392 txs=8/0 age=3d18h44m t=113.128ms
INFO [02-07|11:52:58.857] New block                                index=29897851 id=78183:2982:315b5e gas_used=649,408   txs=6/0 age=3d18h44m t=44.499ms
INFO [02-07|11:52:58.967] New block                                index=29897852 id=78183:3003:e326ea gas_used=2,448,546 txs=7/0 age=3d18h44m t=103.475ms
INFO [02-07|11:52:59.009] New block                                index=29897853 id=78183:3014:6e8888 gas_used=1,155,340 txs=6/0 age=3d18h44m t=41.520ms
INFO [02-07|11:52:59.030] New block                                index=29897854 id=78183:3020:4a3b2f gas_used=146,802   txs=1/0 age=3d18h44m t=21.409ms
INFO [02-07|11:52:59.171] New block                                index=29897855 id=78183:3031:906f48 gas_used=3,025,894 txs=9/0 age=3d18h44m t=140.859ms
INFO [02-07|11:52:59.627] Transaction pool price threshold updated price=220,224,000,000
INFO [02-07|11:52:59.667] New block                                index=29897856 id=78183:3044:7f4056 gas_used=9,240,550 txs=4/0 age=3d18h44m t=495.498ms
INFO [02-07|11:52:59.784] New block                                index=29897857 id=78184:2:df70b3    gas_used=2,136,316 txs=7/0 age=3d18h44m t=116.634ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda2ce2]

goroutine 290 [running]:
github.com/Fantom-foundation/go-opera/txtrace.(*TraceStructLogger).CaptureState(0xc013dabb80, 0xc0138aca80, 0x413, 0xc02e9a82f3, 0x188, 0x0, 0xc02e9a8280, 0x0, 0x0, 0x0, ...)
	/go/go-opera/fct/txtrace/trace_logger.go:205 +0x232
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc01d2b4d00, 0xc02368ecc0, 0xc014b43a40, 0x44, 0xc0, 0xc02bdd5a00, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.9.7-0.20211011130458-d2c87807503f/core/vm/interpreter.go:280 +0x737
github.com/ethereum/go-ethereum/core/vm.run(0xc0138aca80, 0xc02368ecc0, 0xc014b43a40, 0x44, 0xc0, 0x3eb09c327a1f7300, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.9.7-0.20211011130458-d2c87807503f/core/vm/evm.go:82 +0x225
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc0138aca80, 0x160d400, 0xc026715a40, 0x8ad75b77d398f04c, 0xda9867123ea10845, 0x77af45dfcdb61159, 0xc014b43a40, 0x44, 0xc0, 0x150e5b, ...)
	/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.9.7-0.20211011130458-d2c87807503f/core/vm/evm.go:270 +0x80d
github.com/ethereum/go-ethereum/core/vm.opCall(0xc025818108, 0xc01d2b4d00, 0xc02e74dd60, 0xc02e74ddf1, 0x1566a6, 0x151117, 0xc02e74dd60, 0xc02be942c0)
	/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.9.7-0.20211011130458-d2c87807503f/core/vm/instructions.go:663 +0x5cd
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc01d2b4d00, 0xc026715a40, 0xc01a3a2820, 0x44, 0x44, 0xc02bd70f00, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.9.7-0.20211011130458-d2c87807503f/core/vm/interpreter.go:285 +0x519
github.com/ethereum/go-ethereum/core/vm.run(0xc0138aca80, 0xc026715a40, 0xc01a3a2820, 0x44, 0x44, 0x14b3ab5cb156700, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.9.7-0.20211011130458-d2c87807503f/core/vm/evm.go:82 +0x225
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc0138aca80, 0x1610040, 0xc02bd708a0, 0x9d3da601f106b137, 0xf8b62ee54031e506, 0xbc5baca3, 0xc01a3a2820, 0x44, 0x44, 0x182bea, ...)
	/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.9.7-0.20211011130458-d2c87807503f/core/vm/evm.go:270 +0x80d
github.com/Fantom-foundation/go-opera/evmcore.(*StateTransition).TransitionDb(0xc02d2ead90, 0x1640520, 0xc014868000, 0xc022077bc8)
	/go/go-opera/fct/evmcore/state_transition.go:276 +0x50a
github.com/Fantom-foundation/go-opera/evmcore.ApplyMessage(0xc0138aca80, 0x1640520, 0xc014868000, 0xc022077bc8, 0x28c126d4e3be4c25, 0xc02e74cac0, 0xc02bd70100)
	/go/go-opera/fct/evmcore/state_transition.go:168 +0x67
github.com/Fantom-foundation/go-opera/evmcore.applyTransaction(0xc02bd70060, 0xc9d01a5e93c8ca3f, 0x1aa56959dc760364, 0x53663dd0, 0x46e, 0xc02e74c9c0, 0x187f3e, 0xc02e74c980, 0xc01a3a2820, 0x44, ...)
	/go/go-opera/fct/evmcore/state_processor.go:133 +0x44a
github.com/Fantom-foundation/go-opera/evmcore.(*StateProcessor).Process(0xc0204c3588, 0xc013453520, 0xc029597880, 0x1, 0x1631c60, 0xc013dabb80, 0x0, 0x0, 0x0, 0x0, ...)
	/go/go-opera/fct/evmcore/state_processor.go:82 +0x8e5
github.com/Fantom-foundation/go-opera/gossip/blockproc/evmmodule.(*OperaEVMProcessor).Execute(0xc0000c81a0, 0xc013479680, 0x4, 0x1e, 0xc020874000, 0x1, 0x1631c60, 0xc013dabb80, 0x0, 0x0, ...)
	/go/go-opera/fct/gossip/blockproc/evmmodule/evm.go:79 +0x189
github.com/Fantom-foundation/go-opera/gossip.consensusCallbackBeginBlockFn.func1.2.2()
	/go/go-opera/fct/gossip/c_block_callbacks.go:214 +0x94e
github.com/Fantom-foundation/go-opera/gossip.consensusCallbackBeginBlockFn.func1.2.3()
	/go/go-opera/fct/gossip/c_block_callbacks.go:313 +0x78
github.com/Fantom-foundation/lachesis-base/utils/workers.worker(0xc0009895c0, 0xc02c429020)
	/go/pkg/mod/github.com/!fantom-foundation/lachesis-base@v0.0.0-20210721130657-54ad3c8a18c1/utils/workers/workers.go:66 +0x3b
github.com/Fantom-foundation/lachesis-base/utils/workers.(*Workers).Start.func1(0xc00043c2c0)
	/go/pkg/mod/github.com/!fantom-foundation/lachesis-base@v0.0.0-20210721130657-54ad3c8a18c1/utils/workers/workers.go:31 +0x5e
created by github.com/Fantom-foundation/lachesis-base/utils/workers.(*Workers).Start
	/go/pkg/mod/github.com/!fantom-foundation/lachesis-base@v0.0.0-20210721130657-54ad3c8a18c1/utils/workers/workers.go:29 +0x63

```

**Comment by quan8** [comment]
Fix is included in https://github.com/Fantom-foundation/go-opera/tree/release/txtracing/1.0.2-rc.8.
