### ISSUE TITLE
nil panic with custom tracer causes v1.1.1.rc1 to crash

### ISSUE THREAD

**Issue by jhawk28** [Fantom-foundation/go-opera#341]
Stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xc9b478]
goroutine 1494 [running]:
github.com/ethereum/go-ethereum/eth/tracers.(*dbWrapper).pushObject.func2(0xc03e16d658, 0x7ff408034670)
        /root/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.10.8-ftm-rc4/eth/tracers/tracer.go:207 +0xd8
gopkg.in/olebedev/go-duktape%2ev3.goFunctionCall(0x7ff408006840, 0x42135b)
        /root/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/duktape.go:157 +0xb8
gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_pcall_prop(0x7ff408006840, 0x200000000, 0x0)
        _cgo_gotypes.go:2338 +0x48
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp.func1(0xc03e16d628, 0x0, 0x2, 0x7ff408039f10)
        /root/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/api.go:786 +0x71
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp(0xc03e16d628, 0x0, 0x2, 0x2)
        /root/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/api.go:786 +0x3f
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).call(0xc03e44f930, 0x0, 0x1532913, 0x6, 0xc03b008960, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.10.8-ftm-rc4/eth/tracers/tracer.go:643 +0x116
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).GetResult(0xc03e44f930, 0x179c300, 0xc03c6fe480, 0xc03f7c14f8, 0xc03b8c3260, 0x0)
        /root/go/pkg/mod/github.com/!fantom-foundation/go-ethereum@v1.10.8-ftm-rc4/eth/tracers/tracer.go:830 +0x1df
github.com/Fantom-foundation/go-opera/ethapi.(*PublicDebugAPI).traceTx(0xc040766ea0, 0x178e418, 0xc0377d0480, 0x179c300, 0xc03c6fe480, 0xc03b009d50, 0x1624378, 0x1624380, 0xc023a7b110, 0x0, ...)
        /root/go-opera/ethapi/api.go:2176 +0xa7a
github.com/Fantom-foundation/go-opera/ethapi.(*PublicDebugAPI).traceBlock.func1(0xc036a79d30, 0xc040766ea0, 0xc037aa6240, 0xc037a94420, 0xc037795a40, 0x1d, 0x28, 0x17918b8, 0xc01cfe8b30, 0xc0377988c0, ...)
        /root/go-opera/ethapi/api.go:2283 +0x3d0
created by github.com/Fantom-foundation/go-opera/ethapi.(*PublicDebugAPI).traceBlock
        /root/go-opera/ethapi/api.go:2271 +0x37e
```

**Comment by quickchase** [comment]
Bump

**Comment by davidkarim** [comment]
The above crash was seen after sending: debug_traceblocksbynumber

**Comment by quan8** [comment]
Hi @davidkarim , which version are you using? and specific command?
